all: InterfaceComparison

InterfaceComparison: InterfaceComparison.cpp InterfaceComparison.h

	g++ -static -O3 -Wunused-variable -ffast-math -lm -o InterfaceComparison InterfaceComparison.cpp 
clean:
	rm -f InterfaceComparison
